services:
  postgres:
    image: postgres:16-alpine
    container_name: projet-i-postgres
    environment:
      POSTGRES_USER: projet_i
      POSTGRES_PASSWORD: abdy24068
      POSTGRES_DB: projet_i_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projet_i -d projet_i_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
    container_name: projet-i-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET=votre_secret_jwt_tres_securise
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
      - DATABASE_URL=postgresql://projet_i:abdy24068@postgres:5432/projet_i_db
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: projet-i-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
